# For save VM to box file:
# $ vagrant package --base mailing-list
#
# Always before install box, remove old one
# $ vagrant box remove mailing-list
#
require "yaml"

Vagrant.require_version ">= 2.2.8"

Vagrant.configure("2") do |config|
    ### Global configuration

    # SSH
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    config.ssh.insert_key = false

    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
            sudo mkdir -p /root/.ssh
            sudo touch /root/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
            ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
            cd /root/.ssh
            sudo ln -s id_rsa id_rsa.pem
        SHELL
    end

    # VBGuest
    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.auto_update = false
        config.vbguest.installer_hooks[:before_install] = [
            "sudo wget -q -O /tmp/VBoxGuestAdditions_6.1.16.iso https://download.virtualbox.org/virtualbox/6.1.16/VBoxGuestAdditions_6.1.16.iso",
            "sudo mount -o loop /tmp/VBoxGuestAdditions_6.1.16.iso /mnt",
            "sudo /mnt/VBoxLinuxAdditions.run uninstall",
            "umount /mnt"
        ]
    end

    ### VM definitions

    # Generic server
    config.vm.define "mailing-list:172.16.10.10", primary: true do |mailing_list|
        # mailing_list.vm.box = "mailing-list"
        mailing_list.vm.box = "bento/ubuntu-22.04"
        mailing_list.vm.hostname = "mailing-list"
        mailing_list.vm.provider "virtualbox" do |vb|
            vb.name = "mailing-list:172.16.10.10"
            vb.cpus = 2
            vb.memory = 2048
            vb.customize ["modifyvm", :id, "--ioapic", "on"]
        end

        mailing_list.vm.network "private_network", ip: "172.16.10.10"
    end
end
